import shoe from "../assets/images/png/gry_shoe.png";
import gry_start from "../assets/images/png/5_ry_start.png";
import red_start from "../assets/images/png/red_shoe.png";
import offer from "../assets/images/png/10_Off.png";
import new_tag from "../assets/images/png/New_lable.png";
import cart from "../assets/images/svg/cart.svg";

export const shoeary = [
  {
    img1: red_start,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: shoe,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: red_start,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: shoe,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: red_start,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: shoe,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: red_start,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: shoe,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: red_start,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: shoe,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: red_start,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: shoe,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: red_start,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
  {
    img1: shoe,
    img2: offer,
    img3: new_tag,
    para1: "Quickiins Mens Shoes",
    para2: "$90.00",
    para3: "$70.00",
    img4: cart,
    imgGrayStart: gry_start,
  },
];
